### ISSUE TITLE
no attribute 'create_dataset'

### ISSUE THREAD

**Issue by AsadSeeker** [Yichabod/natural_disaster_pred#1]
hello ... i am working to run your code. in "landslide_detection_main.py" line 10, arrtibute error occurs because create_dataset is not the attribute of the library 'dataset'. i looked into its documentation which is here: https://dataset.readthedocs.io/en/latest/api.html
can you please tell me the how can i run this.

**Comment by saeedojaghi** [comment]
I have this issue also

**Comment by 5olitude** [comment]
> hello ... i am working to run your code. in "landslide_detection_main.py" line 10, arrtibute error occurs because create_dataset is not the attribute of the library 'dataset'. i looked into its documentation which is here: https://dataset.readthedocs.io/en/latest/api.html
> can you please tell me the how can i run this.

The reason why you got this error is that the author named the file as create_dataset.py  and in landslide_detection.py he imported it with the name  dataset .So if you want to run the script successfully just rename the create_dataset.py into dataset.py 

alternatively  in your case rename import dataset into create_dataset.py
